#!/bin/sh
export CYCLONEDDS_URI='<CycloneDDS><Domain><General><AllowMulticast>true</AllowMulticast><Interfaces><NetworkInterface name="lo" /></Interfaces></General></Domain></CycloneDDS>'
export dds_prompt='loopback'