leg_balancer:
  kp: 20.0
  ki: 6.0
  kd: 1.0
  tau_min: -15.0
  tau_max: 15.0 
  setpoint: -1.9
  hip:
    kp: 3.0
    ki: 0.003
    kd: 1.0
    tau_min: -15.0
    tau_max: 15.0 
    setpoint: 0.0
  thigh:
    kp: 3.0
    ki: 0.003
    kd: 1.0
    tau_min: -15.0
    tau_max: 15.0 
    setpoint: 0.3
  calf:
    kp: 3.0
    ki: 0.003
    kd: 1.0
    tau_min: -15.0
    tau_max: 15.0 
    setpoint: -1.4