leg_balancer:
  tau_min: -10.0
  tau_max: 10.0

  hip:
    enabled: false
    setpoint: 0.0
    position:
      K: 10.0
      Ti: 0.0
      Td: 0.0
      N: 10.0
      Beta: 1.0
      Tr: 10.0
      
    velocity:
      K: 3.0
      Ti: 2.0
      Td: 0.0
      N: 10.0
      Beta: 1.0
      Tr: 10.0

  thigh:
    enabled: false
    setpoint: 0.3
    position:
      K: 20.0
      Ti: 0.0
      Td: 0.0
      N: 10.0
      Beta: 1.0
      Tr: 10.0    
    velocity:
      K: 3.6
      Ti: 2.0
      Td: 0.0
      N: 10.0
      Beta: 1.0
      Tr: 10.0

  calf:
    enabled: true
    setpoint: -1.4
    position:
      K: 20.0
      Ti: 0.0
      Td: 0.0
      N: 10.0
      Beta: 1.0
      Tr: 10.0
    velocity:
      K: 3.6
      Ti: 2.0
      Td: 0.0
      N: 10.0
      Beta: 1.0
      Tr: 10.0

square_wave:
  logfile: ./square_wave.csv
  K: 0.8
  Ti: 0.6
  Td: 0.0
  dq: 3.0
  tau_min: -10.0
  tau_max: 10.0
  switch_period: 400
  periods: 4
  N: 10.0
  Beta: 1.0
  Tr: 10.0

sine_wave:
  logfile: ./sine_wave.csv
  K: 0.6
  Ti: 0.6
  Td: 0.0
  tau_min: -10.0
  tau_max: 10.0
  period_samples: 500
  periods: 4
  factor: 4.0
  N: 10.0
  Beta: 1.0
  Tr: 10.0

cascaded_sine_wave:
  logfile: ./cascaded_sine_wave.csv
  position:
    K: 20.0
    Ti: 0.0
    Td: 0.0
    N: 10.0
    Beta: 1.0
    Tr: 10.0  
  velocity:
    K: 0.6
    Ti: 0.6
    Td: 0.0
    N: 10.0
    Beta: 1.0
    Tr: 10.0
  pos_min: 3.0
  pos_max: 0.0
  tau_min: -20.0
  tau_max: 20.0
  period_samples: 1200
  periods: 2
  outer_factor: 10

cascaded_sine_wave_tmp:
  logfile: ./cascaded_sine_wave.csv
  position:
    K: 5.0
    Ti: 0.0
    Td: 0.0
    N: 10.0
    Beta: 1.0
    Tr: 10.0
  velocity:
    K: 3.7
    Ti: 2.0
    Td: 0.0
    N: 10.0
    Beta: 1.0
    Tr: 10.0

  pos_min: -0.7
  pos_max: 0.7
  tau_min: -20.0
  tau_max: 20.0
  period_samples: 100
  periods: 4
  outer_factor: 10

old:
  hip:
    K: 14.0
    Ti: 2.0
    Td: 1.0
    setpoint: 0.0
    N: 10.0
    Beta: 1.0
    Tr: 10.0

  thigh:
    K: 12.0
    Ti: 2.0
    Td: 1.0
    setpoint: 1.5
    N: 10.0
    Beta: 1.0
    Tr: 10.0

  calf:
    K: 12.0
    Ti: 2.0
    Td: 1.0
    setpoint: -1.4
    N: 10.0
    Beta: 1.0
    Tr: 10.0

  _thigh:
    K: 10.0
    Ti: 2.0
    Td: 1.0
    setpoint: 0.3
    N: 10.0
    Beta: 1.0
    Tr: 10.0

  _calf:
    K: 10.0
    Ti: 2.0
    Td: 1.0
    setpoint: -1.4
    N: 10.0
    Beta: 1.0
    Tr: 10.0