leg_balancer:
  tau_min: -10.0
  tau_max: 10.0

  hip:
    enabled: false
    setpoint: 0.0
    position:
      kp: 10.0
      ki: 0.0
      kd: 0.0
    velocity:
      kp: 3.0
      ki: 2.0
      kd: 0.0

  thigh:
    enabled: false
    setpoint: 0.3
    position:
      kp: 20.0
      ki: 0.0
      kd: 0.0
    velocity:
      kp: 3.6
      ki: 2.0
      kd: 0.0

  calf:
    enabled: true
    setpoint: -1.4
    position:
      kp: 20.0
      ki: 0.0
      kd: 0.0
    velocity:
      kp: 3.6
      ki: 2.0
      kd: 0.0

square_wave:
  logfile: ./square_wave.csv
  kp: 1.0
  ki: 0.8
  kd: 0.0
  dq: 3.0
  tau_min: -10.0
  tau_max: 10.0
  switch_period: 400
  periods: 4

sine_wave:
  logfile: ./sine_wave.csv
  kp: 0.8
  ki: 0.7
  kd: 0.0
  tau_min: -10.0
  tau_max: 10.0
  period_samples: 500
  periods: 4
  factor: 4.0

cascaded_sine_wave:
  logfile: ./cascaded_sine_wave.csv
  position:
    kp: 20.0
    ki: 0.0
    kd: 0.0
  velocity:
    kp: 0.6
    ki: 0.6
    kd: 0.0
  pos_min: 3.0
  pos_max: 0.0
  tau_min: -20.0
  tau_max: 20.0
  period_samples: 1200
  periods: 4
  outer_factor: 10

cascaded_sine_wave_tmp:
  logfile: ./cascaded_sine_wave.csv
  position:
    kp: 5.0
    ki: 0.0
    kd: 0.0
  velocity:
    kp: 3.7
    ki: 2.0
    kd: 0.0
  pos_min: -0.7
  pos_max: 0.7
  tau_min: -20.0
  tau_max: 20.0
  period_samples: 800
  periods: 4
  outer_factor: 10

old:
  hip:
    kp: 14.0
    ki: 2.0
    kd: 1.0
    setpoint: 0.0

  thigh:
    kp: 12.0
    ki: 2.0
    kd: 1.0
    setpoint: 1.5

  calf:
    kp: 12.0
    ki: 2.0
    kd: 1.0
    setpoint: -1.4

  _thigh:
    kp: 10.0
    ki: 2.0
    kd: 1.0
    setpoint: 0.3
  _calf:
    kp: 10.0
    ki: 2.0
    kd: 1.0
    setpoint: -1.4