# Parameters for the square wave experiment
square_wave:
  # Log file to save measurements and signals in
  logfile: ./square_wave-calf.csv 
  
  # Gains for the PID controller
  K: 2.25
  Ti: 0.20
  Td: 0.0025
  N: 20.0
  Beta: 1.0
  Tr: 0.075

  # Velocity setpoint
  dq: 2.5

  # Torque limits
  tau_min: -10.0
  tau_max: 10.0

  # Experiment duration in measurement periods
  periods: 4

  # Timer ticks per period
  ticks_per_period: 400

  # Control period in milliseconds
  ms_per_tick: 2
  
  # The joint to be controlled
  leg: front_left
  joint: calf
  
  # Initial joint position (set to null to disable)
  initial:
    hip: 0.0
    thigh: 3.0
    calf: -2.7

# Parameters for the sine wave experiment
sine_wave:
  # Log file to save measurements and signals in
  logfile: ./sine_wave-calf.csv 
  
  # Gains for the PID controller
  K: 2.25
  Ti: 0.20
  Td: 0.0025
  N: 20.0
  Beta: 1.0
  Tr: 0.075

  # Velocity factor
  dq_factor: 3.0

  # Torque limits
  tau_min: -10.0
  tau_max: 10.0

  # Experiment duration in measurement periods
  periods: 4

  # Timer ticks per period
  ticks_per_period: 400

  # Control period in milliseconds
  ms_per_tick: 2
  
  # The joint to be controlled
  leg: front_left
  joint: calf
  
  # Initial joint position (set to null to disable)
  initial:
    hip: 0.0
    thigh: 3.0
    calf: -2.7

# Parameter for the cascaded sine wave experiment
cascaded_sine_wave:
  # Log file to save measurements and signals in
  logfile: ./cascaded_sine_wave-calf.csv

  # Gains for the position (i.e. outer) PID controller
  position:
    K: 30.0
    Ti: 0.10
    Td: 0.001
    N: 20.0
    Beta: 1.0
    Tr: 0.05

  # Gains for the velocity (i.e. inner) PID controller
  velocity:
    K: 2.25
    Ti: 0.20
    Td: 0
    N: 20.0
    Beta: 1.0
    Tr: 0.075

  # Position limits (bounds of sine curve)
  pos_min: -2.65
  pos_max: -1.15

  # Torque limits
  tau_min: -20.0
  tau_max: 20.0

  # Experiment duration in measurement periods
  periods: 4

  # Timer ticks per period
  ticks_per_period: 1200

  # Control period in milliseconds
  ms_per_tick: 2
  
  # The relative execution rate of the inner to the outer controller
  outer_factor: 10
  
  # The joint to be controlled
  leg: front_left
  joint: calf

  # Initial joint position (set to null to disable)
  initial:
    hip: 0.0
    thigh: 3.0
    calf: -1.9
  