# Stand height parameters
stand_height:
  # Hip joint controller parameters
  hip:
    # Gains for the position (i.e. outer) PID controller
    position:
      K: 14.0
      Ti: 0.0
      Td: 0.0
      N: 15.0
      Beta: 1.0
      Tr: null

    # Gains for the velocity (i.e. inner) PID controller
    velocity:
      K: 0.5
      Ti: 0.05
      Td: 0.0
      N: 15.0
      Beta: 1.0
      Tr: null

    # The relative execution rate of the inner to the outer controller
    outer_factor: 10
    
    # Torque limits
    tau_min: -20.0
    tau_max: 20.0
    
    # Programmatic motion speed (in rad/s)
    motion_speed: 0.8

  # Thigh joint controller parameters
  thigh:
    # Gains for the position (i.e. outer) PID controller
    position:
      K: 19.0
      Ti: 0.0
      Td: 0.0
      N: 25.0
      Beta: 1.0
      Tr: null # sqrt(t_i * t_d)

    # Gains for the velocity (i.e. inner) PID controller
    velocity:
      K: 0.38
      Ti: 0.086
      Td: 0.000
      N: 20.0
      Beta: 1.0
      Tr: null # sqrt(t_i * t_d)

    # The relative execution rate of the inner to the outer controller
    outer_factor: 10
    
    # Torque limits
    tau_min: -20.0
    tau_max: 20.0
    
    # Desired motion speed (in rad/s)
    motion_speed: 0.8

  # Calf joint controller parameters
  calf:
    # Gains for the position (i.e. outer) PID controller
    position:
      K: 16.0
      Ti: 0.0
      Td: 0.0
      N: 20.0
      Beta: 1.0
      Tr: 0.05

    # Gains for the velocity (i.e. inner) PID controller
    velocity:
      K: 0.9
      Ti: 0.025
      Td: 0.0
      N: 20.0
      Beta: 1.0
      Tr: 0.075

    # The relative execution rate of the inner to the outer controller
    outer_factor: 10
    
    # Torque limits
    tau_min: -20.0
    tau_max: 20.0
    
    # Programmatic motion speed (in rad/s)
    motion_speed: 0.8

  # Control period in milliseconds
  ms_per_tick: 2
  
  # Joint angle setpoints for sitdown pose
  sit_down:
    hip: 0.0
    thigh: 0.785
    calf: -1.57