//
// Created by ubuntu on 3/20/26.
//

#ifndef RTSC_UNITREE_ROS2_GO_CONSTANTS_H
#define RTSC_UNITREE_ROS2_GO_CONSTANTS_H
#include <cstdint>

namespace common::constants
{
    constexpr uint8_t
        FRONT_RIGHT_INDEX = 0,
        FRONT_LEFT_INDEX = 1,
        BACK_RIGHT_INDEX = 2,
        BACK_LEFT_INDEX = 3;

    constexpr uint8_t
        HIP_OFFSET = 0,
        THIGH_OFFSET = 1,
        CALF_OFFSET = 2,
        MOTOR_MAX_OFFSET = 3;

    constexpr uint8_t
        FR_HIP = (FRONT_RIGHT_INDEX * MOTOR_MAX_OFFSET) + HIP_OFFSET,
        FR_THIGH = (FRONT_RIGHT_INDEX * MOTOR_MAX_OFFSET) + THIGH_OFFSET,
        FR_CALF = (FRONT_RIGHT_INDEX * MOTOR_MAX_OFFSET) + CALF_OFFSET,
        FL_HIP = (FRONT_LEFT_INDEX * MOTOR_MAX_OFFSET) + HIP_OFFSET,
        FL_THIGH = (FRONT_LEFT_INDEX * MOTOR_MAX_OFFSET) + THIGH_OFFSET,
        FL_CALF = (FRONT_LEFT_INDEX * MOTOR_MAX_OFFSET) + CALF_OFFSET,
        BR_HIP = (BACK_RIGHT_INDEX * MOTOR_MAX_OFFSET) + HIP_OFFSET,
        BR_THIGH = (BACK_RIGHT_INDEX * MOTOR_MAX_OFFSET) + THIGH_OFFSET,
        BR_CALF = (BACK_RIGHT_INDEX * MOTOR_MAX_OFFSET) + CALF_OFFSET,
        BL_HIP = (BACK_LEFT_INDEX * MOTOR_MAX_OFFSET) + HIP_OFFSET,
        BL_THIGH = (BACK_LEFT_INDEX * MOTOR_MAX_OFFSET) + THIGH_OFFSET,
        BL_CALF = (BACK_LEFT_INDEX * MOTOR_MAX_OFFSET) + CALF_OFFSET;

    constexpr uint8_t
        LEG_MAX_INDEX = BACK_LEFT_INDEX,
        MOTOR_MAX_INDEX = BL_CALF;
}

#endif //RTSC_UNITREE_ROS2_GO_CONSTANTS_H
